##
## Copyright 2022 Zachary Espiritu
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

from abc import ABC, abstractmethod


from typing import Generic, TypeVar


KeyType = TypeVar("KeyType")
EdsType = TypeVar("EdsType")
PlaintextInputType = TypeVar("PlaintextInputType")
TokenInputType = TypeVar("TokenInputType")
QueryOutputType = TypeVar("QueryOutputType")


class RevealingEDS(
    ABC,
    Generic[KeyType, PlaintextInputType, EdsType, TokenInputType, QueryOutputType],
):
    """
    An interface representing a generic encrypted data structure.

    This interface is intended to be used to define other types of
    encrypted data structures. See :class:`EDX` and :class:`EMM` for
    more specific instantiations of data structures.
    """

    @abstractmethod
    def generate_key(self) -> KeyType:
        """
        Generates a key for the encrypted data structure scheme.

        :return: a key
        """
        ...

    @abstractmethod
    def encrypt(self, key: KeyType, plaintext_ds: PlaintextInputType) -> bytes:
        """
        Encrypts the given plaintext data structure with the given key
        and returns a byte string representing the encrypted data structure.

        :param key: the key to encrypt with, as generated from :func:`generate_key`
        :param plaintext_ds: the plaintext structure to encrypt
        :return: a serialized encrypted data structure
        """
        ...

    @abstractmethod
    def load_eds(self, eds_bytes: bytes) -> EdsType:
        """
        Deserializes a byte string representing an encrypted data structure
        into the type needed by the :func:`query` algorithm.

        :param eds_bytes: a serialized encrypted data structure from :func:`encrypt`
        :return: a deserialized version of the encrypted data structure
        """
        ...

    @abstractmethod
    def token(self, key: KeyType, keyword: TokenInputType) -> bytes:
        """
        Generates a search token for the given key and keyword.

        :param key: the key to encrypt with
        :param keyword: the keyword to query the encrypted data structure with
        :return: a search token
        """
        ...

    @abstractmethod
    def query(self, token: bytes, eds: EdsType) -> QueryOutputType:
        """
        Returns a result for the given search token queried over the
        given encrypted data structure.

        :param token: a search token generated by :func:`token`
        :param eds: the encrypted data structure from :func:`load_eds`
        :return: a list of plaintext values
        """
        ...
